import {
  Leaf,
  Apple,
  Star,
  MoreHorizontal,
  Dice5,
  PawPrint,
  Gamepad2,
  HandHeart,
  Wrench,
  Car,
  Glasses,
  BookOpen,
  Package,
  Gift,
  CreditCard,
  Send,
  Plane,
  Briefcase,
  Newspaper,
  CupSoda,
  Pizza,
  BarChart3,
  Phone,
  Music,
  Users,
  MonitorSmartphone,
  Shirt,
  Sparkles,
  Wallet,
  Dumbbell,
  Stethoscope,
  Book,
  Utensils,
  UtensilsCrossed,
  ShoppingCart,
  Cookie,
  Bus,
  Home,
  Lamp,
  ShoppingBag,
  Sofa,
  PiggyBank,
  LineChart,
  BadgeDollarSign,
  ArrowDownCircle,
  ArrowDownLeft,
  Box,
  Coffee,
  CircleOff,
} from "lucide-react";

const iconMap: Record<string, React.FC<{ className?: string }>> = {
  leaf: Leaf,
  apple: Apple,
  star: Star,
  "more-horizontal": MoreHorizontal,
  "dice-5": Dice5,
  "paw-print": PawPrint,
  "gamepad-2": Gamepad2,
  "hand-heart": HandHeart,
  wrench: Wrench,
  car: Car,
  glass: Glasses,
  "book-open": BookOpen,
  package: Package,
  gift: Gift,
  "credit-card": CreditCard,
  send: Send,
  plane: Plane,
  briefcase: Briefcase,
  newspaper: Newspaper,
  "cup-soda": CupSoda,
  pizza: Pizza,
  "bar-chart-3": BarChart3,
  phone: Phone,
  music: Music,
  users: Users,
  "monitor-smartphone": MonitorSmartphone,
  shirt: Shirt,
  sparkles: Sparkles,
  wallet: Wallet,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  book: Book,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "shopping-cart": ShoppingCart,
  cookie: Cookie,
  bus: Bus,
  home: Home,
  lamp: Lamp,
  "shopping-bag": ShoppingBag,
  sofa: Sofa,
  "piggy-bank": PiggyBank,
  "line-chart": LineChart,
  "badge-dollar-sign": BadgeDollarSign,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-down-left": ArrowDownLeft,
  box: Box,
  coffee: Coffee,
  default: CircleOff,
};

type Props = {
  symbol: string | undefined;
  className?: string;
};

export function CategoryIcon({ symbol, className }: Props) {
  if (!symbol) {
    return <span className={className}>?</span>;
  }
  
  const Icon = iconMap[symbol];

  return <Icon className={className} />;
}
